### ISSUE TITLE
Getting errors when trying run HelloWorld KSP

### ISSUE THREAD

**Issue by WyldWilly** [dgalatzerlevy/kspScripts#1]
Hi, I just downloaded this about 2hrs ago, and when I try a simple script
import krpc
conn = krpc.connect()
print(conn.krpc.get_status().verson)

I keep getting the following. I checked and I am running Python 3.6.0 and also have the latest protobuf. Not sure if it is something else. But saw that you had just done a new commit about that same time. Any thoughts appreciated. I am able to run other python scripts and processes without errors, seems only to happen when I try kRPC. Thanks, WMC

$ python KSPGetConnect.py
Traceback (most recent call last):
  File "KSPGetConnect.py", line 1, in <module>
    import krpc
  File "E:\Programs\Python\Python36-32\lib\site-packages\krpc\__init__.py", line 1, in <module>
    from krpc.connection import Connection
  File "E:\Programs\Python\Python36-32\lib\site-packages\krpc\connection.py", line 3, in <module>
    from krpc.encoder import Encoder
  File "E:\Programs\Python\Python36-32\lib\site-packages\krpc\encoder.py", line 3, in <module>
    from google.protobuf.internal import encoder as protobuf_encoder
  File "E:\Programs\Python\Python36-32\lib\site-packages\google\protobuf\internal\encoder.py", line 73, in <module>
    from google.protobuf.internal import wire_format
  File "E:\Programs\Python\Python36-32\lib\site-packages\google\protobuf\internal\wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "E:\Programs\Python\Python36-32\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by dgalatzerlevy** [comment]
I think we chatted on Facebook. Best we could figure it was a config error in python. You could also try asking on kRPC's github. Sorry I couldn't help more

**Comment by WyldWilly** [comment]
No worry! :)

Sent from my iPhone YF-23

________________________________
